name: pdd
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.7.4=hf0a4a13_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h313beb8_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.18=h27ca646_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.1=hfb2fe0b_2
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=py312hca03da5_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=5.9.0=py312h80987f9_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.4=h99e199e_1
  - readline=8.2=h1a28f6b_0
  - setuptools=69.5.1=py312hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.1=py312h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aiohappyeyeballs==2.3.2
      - aiohttp==3.10.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.32.0
      - anyio==4.4.0
      - attrs==23.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==5.4.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - distro==1.9.0
      - docopt==0.6.2
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.19.1
      - google-api-python-client==2.139.0
      - google-auth==2.32.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.7.2
      - googleapis-common-protos==1.63.2
      - grpcio==1.65.1
      - grpcio-status==1.62.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.0
      - huggingface-hub==0.24.3
      - idna==3.7
      - ipython==8.12.3
      - jinja2==3.1.4
      - jiter==0.5.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - langchain==0.2.11
      - langchain-anthropic==0.1.21
      - langchain-community==0.2.10
      - langchain-core==0.2.24
      - langchain-google-genai==1.0.8
      - langchain-openai==0.1.19
      - langchain-text-splitters==0.2.2
      - langsmith==0.1.93
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - mdurl==0.1.2
      - mistune==3.0.2
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - numpy==1.26.4
      - openai==1.37.1
      - orjson==3.10.6
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - pipreqs==0.5.0
      - proto-plus==1.24.0
      - protobuf==4.25.4
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.19.1
      - rsa==4.9
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.31
      - stack-data==0.6.3
      - tenacity==8.5.0
      - tiktoken==0.7.0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uritemplate==4.1.1
      - urllib3==2.2.2
      - webencodings==0.5.1
      - yarg==0.1.9
      - yarl==1.9.4
prefix: /Applications/anaconda3/envs/pdd
