[build-system]
requires = [
    "setuptools>=43.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "pdd"
version = "0.2.1"
description = "PDD (Prompt-Driven Development) Command Line Interface"
readme = "README.md"
authors = [
    { name = "Greg Tanaka", email = "glt@alumni.caltech.edu" }
]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
keywords = [
    "prompt-driven development",
    "code generation",
    "AI",
    "LLM",
    "unit testing",
    "software development"
]
dependencies = [
    "GitPython==3.1.43",
    "anthropic==0.34.2",
    "click==8.1.7",
    "fuzzywuzzy==0.18.0",
    "langchain==0.3.1",
    "langchain_anthropic==0.2.1",
    "langchain_community==0.3.1",
    "langchain_core==0.3.7",
    "langchain_fireworks==0.2.0",
    "langchain_google_genai==2.0.0",
    "langchain_groq==0.2.0",
    "langchain_openai==0.2.1",
    "langchain_together==0.2.0",
    "pandas==2.2.3",
    "pydantic==2.9.2",
    "pytest==8.3.2",
    "rich==13.9.1",
    "tiktoken==0.7.0",
    "build",
    "python-Levenshtein",
    "pytest-cov",
    "langchain_ollama",
    "langchain-google-vertexai"
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/gltanaka/pdd"
Repository = "https://github.com/gltanaka/pdd.git"

[project.scripts]
pdd = "pdd.cli:cli"

[tool.setuptools.packages.find]
include = ["pdd*"]

[tool.setuptools.package-data]
"pdd" = [
    "prompts/*_LLM.prompt",
    "data/*",
    "*.zsh"
]
